[package]
name = "avian_pickup"
version = "0.1.0"
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"

[features]
default = ["dev"]
serialize = [
    "dep:serde",
    "bevy/serialize",
    "avian3d/serialize",
]
dev = [
    "bevy/dynamic_linking"
]

[dependencies]
avian3d = { git = "https://github.com/Jondolf/bevy_xpbd", branch = "avian"}
serde = { version = "1.0", optional = true}

[dependencies.bevy]
version = "0.14.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

