error_on_line_overflow = true
error_on_unformatted = true
version = "Two"
imports_granularity = "Crate"
comment_width = 150
max_width = 150
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
reorder_impl_items = true
unstable_features = true
wrap_comments = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 150
